describe("utils.str", function()
  local str = require("utils.str")

  it("truncates by display width without splitting multibyte text", function()
    assert.equals("hello", str.trunc("hello", 10))
    assert.equals("", str.trunc("hello", 0))

    local result = str.trunc("󰈚 hello world", 5)
    assert.is_true(vim.fn.strdisplaywidth(result) <= 5)
    assert.is_truthy(result:find("…", 1, true))
    assert.equals("󰈚", vim.fn.strcharpart(result, 0, 1))
    assert.is_true(vim.fn.strchars(result) > 0)
  end)

  it("right-pads short text and preserves wider text", function()
    assert.equals("ab   ", str.rpad("ab", 5))
    assert.equals("hello", str.rpad("hello", 5))
    assert.equals("hello world", str.rpad("hello world", 5))
    assert.equals("hi      ", str.fill_line("hi", 8))
  end)
end)
