describe("service.config", function()
  local cfg = require("service.config")

  it("defaults missing mason packages to auto-install on enable", function()
    assert.equals("auto", cfg.missing_package_policy)
  end)

  it("uses explicit enabled and disabled service icons", function()
    assert.equals("", cfg.icons.enabled)
    assert.equals("", cfg.icons.disabled)
    assert.equals("", cfg.icons.warning)
    assert.equals("", cfg.icons.error)
  end)

  it("uses explicit expand and collapse arrows", function()
    assert.equals("", cfg.icons.expanded)
    assert.equals("", cfg.icons.collapsed)
  end)

  it("exposes service manager table layout settings", function()
    assert.equals(1, cfg.table.cell_padding)
    assert.equals(2, cfg.table.indent)
    assert.equals("  ", cfg.table.separator)
  end)

  it("exposes service manager section and help settings", function()
    assert.equals(1, cfg.layout.section_margin)
    assert.equals("Service", cfg.labels.columns.service)
    assert.is_true(#cfg.help.sections > 0)
  end)
end)
